# Generated by Django 5.2.6 on 2025-10-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Project_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Project_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Project_3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gfg',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='leetcode',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='protfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Python Developer', 'Python developer'), ('AI/ML Engineer', 'AI/ML Engineer'), ('MERN Stack', 'MERN Stack'), ('Project Manager', 'Project Manager'), ('Perparaing', 'Perparaing')], default='Perparaing'),
        ),
    ]
